#!/bin/bash
certs_in=/scripts/certs
certs_out=/etc/ssl/apache

# Make sure all directories exists
mkdir -p $certs_out/certs
mkdir -p $certs_out/keys
mkdir -p $certs_out/intermediates

chmod 700 -R $certs_out

if [[ ! -d $certs_in ]]; then
    echo "$certs_in doesn't exist!"
    exit
fi

if ls $certs_in/*.key > /dev/null 2>&1; then
    cp $certs_in/*.key $certs_out/keys/
    echo "Copying keys..."
else
    echo "Key-File not found!"
    exit $?
fi

if ls $certs_in/*.crt > /dev/null 2>&1; then
    cp $certs_in/*.crt $certs_out/certs/
    echo "Copying certifates..."
else
    echo "Certificate-File not found!"
    exit $?
fi

if ls $certs_in/*.ca-bundle > /dev/null 2>&1; then
    cp $certs_in/*.ca-bundle $certs_out/intermediates/
    echo "Copying ca-bundles..."
fi