#!/bin/bash
INTERVAL=1
STATSD_PATH=docker.seu
STATSD_PORT=8125
LOG_LEVEL=1

# Set default values
[ -z "$STATSD_STATUS_NAME" ] && STATSD_STATUS_NAME=$(cat /proc/self/cgroup | grep 'docker' | sed 's/^.*\///' | tail -n1 | grep -Eo ^[^\.]+)
[ -z "$STATSD_STATUS_SERVER" ] && STATSD_STATUS_SERVER=graphite.hh.iteratec.de

# Run if activated
if [[ -n "$STATSD_STATUS_REPORT" && "$STATSD_STATUS_REPORT" =~ (T|t)rue ]]
then
	# Log
	echo "Starting status reports..."
	echo "Name: $STATSD_STATUS_NAME"
	echo "Path: $STATSD_PATH.$STATSD_STATUS_NAME"
	echo "Server: $STATSD_STATUS_SERVER"

	while true; do
		echo "$STATSD_PATH.$STATSD_STATUS_NAME.availbility:1|c" | nc -w 1 -u $STATSD_STATUS_SERVER $STATSD_PORT
		[ "$LOG_LEVEL" -gt "1" ] && echo "Sent status... [$STATSD_PATH.$STATSD_STATUS_NAME.availbility]" 
		sleep "$INTERVAL"
	done
else
	echo "Not starting status reports. Service deactivated!"
fi
